### PR TITLE
Add examples for FloatLiteral

### PR DESCRIPTION
**Pull request by StitchyPie**

### CODE REVIEW

**Comment by mojodojodev** [comment]
Hi @StitchyPie thanks very much again for your contribution, I need to the `.ipynb` file though to be able to make changes if the syntax ever changes in the future.

By the way you can [connect to your playground from VS Code](https://mojodojo.dev/guides/general/mojo_playground_vscode.html) and that makes it way easier to save notebooks locally

**Comment by StitchyPie** [comment]
Oo okay thank you that will make things much faster, hmm when trying to select my kernel server on VS code I need to enter a password. What is that password since I logged in using Google and that password does not work.

**Comment by StitchyPie** [comment]
OO I see thank you got it will push later today XD.

**Comment by mojodojodev** [comment]
Awesome thanks!

**Pull request merged**
